---
- name: Install packages
  ansible.builtin.apt:
    name:
      - software-properties-common
      - libcurl4-gnutls-dev
      - tmux
    state: present
    update_cache: true

- name: Add multiverse repos and i386 arch
  ansible.builtin.shell: >
    add-apt-repository multiverse -y &&
    dpkg --add-architecture i386
  args:
    creates: /var/lib/dpkg/arch
